example_func_test.go, example_test.go, example_var_test.go
This pull request adds three examples of using HIL - one for simple arithmetic, one with variable access, and one with a function call. They are added as GoDoc examples so they will run as part of the tests.
=> Add example HIL library usage to GoDoc

.gitignore, ast/ast.go, ast/index.go, ast/index_test.go, ast/scope.go, ast/scope_test.go, ast/type_string.go, ast/variable_access_test.go, check_types.go, check_types_test.go, eval.go, eval_test.go, lang.y, lex.go, parse_test.go, y.go, y.output
This adds support for indexing into variables of the new type "List". The syntax is typical C-style array syntax, so for example, the following is valid for interpolating the element of the list in variable `foo` at position 1:
```
"${foo[1]}"
```
There is a restriction that lists must be homogenous in type. This is to enable the type checker to work without having to actually perform the indexing operation. During discussion there was no compelling use case for lists of heterogenous types - this is open for discussion in future though if one is found.
=> Add support for indexing into variables

check_types.go
This commit changes the error message returned when the arguments to concat type check as something other than a string, to indicate that it is the entire HIL expression that needs to result in a string.
The previous behaviour made debugging in consumers difficult when the expression consisted of a function which took a string as an argument and returned something other than a string.
=> Improve error when concat output is not a string

builtins.go, eval.go, eval_test.go
Needed in Terraform to allow float math involving variables, because
variables are all strings.
=> Add implicit conversion of string to float

check_types.go, eval.go, eval_test.go
In order to allow outputs which interpolate to lists to resolve correctly in Terraform, and to allow the potential to return maps, we need to break the model of always returning a string from interpolations.
The best way to do this while maintaining backwards compatibility appears to be the following precedence:
Assuming we have a scope which looks like the following:
```
Variables:
var.alist = ["hello", "world"]
Functions:
// None except the builtins
```
The following rules apply:
```
Input: "${var.alist}"
Output from hil.Eval(...) (interface{}, Type, error):
[]ast.Variable{
ast.Variable{
Type: ast.TypeString,
Value: "hello",
},
ast.Variable{
Type: ast.TypeString,
Value: "world",
},
},
ast.TypeList,
nil
```
```
Input: "${var.alist[0]} ${var.alist[1]}"
Output from hil.Eval(...) …
```
=> Allow HIL evaluation to return a TypeList

ast/ast.go, ast/index.go, ast/index_test.go, ast/variables_helper.go, check_types.go, check_types_test.go, eval.go, eval_test.go, y.go
This adds support for indexing into variables of the new type "Map". The syntax is typical Go-style map syntax, so for example, the following is valid for interpolating the value of the map foo at key "bar":
`${foo["bar"]}`
There is a restriction that map values must be homogenous in type. This is to enable the type checker to work without having to actually perform the indexing operation. This is a similar restriction to that placed on lists.
During discussion there was no compelling use case for maps or lists of heterogenous types - this is open for discussion in future though if one is found.
This also expands out the range of test cases covered for lists during type checking and evaluation to include empty lists.
=> Add support for indexing map variables

convert.go, convert_test.go
This adds convenience functions for converting a Go type such as string, []interface{} and map[string]interface{} into their ast.Variable-based representations for use in interpolations.
=> Add functions to convert Go to HIL structures

convert.go, convert_test.go
Because of an awkward backward compatibility construct in mapstructure when using WeakDecode, the test added in this commit fails without the change
to use Decode over WeakDecode, in the following manner:
```
$ go test ./...
--- FAIL: TestInterfaceToVariable (0.00s)
convert_test.go:181: empty list:
Expected: {Variable (TypeList): []}
Got: {Variable (TypeMap): map[]}
FAIL
FAIL	github.com/hashicorp/hil	0.008s
ok  	github.com/hashicorp/hil/ast	0.007s
```
This PR fixes the test, and leads to behaviour which follows the principle of least surprise: empty lists are no longer converted to empty maps!
=> Fix conversion for empty interface slices

convert.go, convert_test.go
The previous fix lacked some nuance - we fixed empty lists at the expense of other primitive types. Instead of using Decode, we now defeat the backward compatibility mechanism in mapstructure with a DecodeHook instead.
cc @phinze, @mitchellh
=> Use WeakDecode for conversions

convert.go, convert_test.go
Previously this fix only applied to `[]interface{}`, but there are places in Terraform where we use the `interfaceToHILVariable` function with `[]string`, which was erroneously converting `[]string{}` to `map[string]interface{}{}` in order to preserve backwards compatibility. We now check for `[]string` in addition to `[]interface{}` in our workaround for this.
cc @phinze, @mitchellh
=> Defeat mapstructure backward compat for []string

ast/ast.go, check_types.go
This results in nicer error mesages when type checking fails in Terraform:
```
$ terraform apply
There are warnings and/or errors related to your configuration. Please
fix these before continuing.
Errors:
* At column 3, line 1: join: argument 1 should be TypeList, got TypeString in:
${join(",", var.astring)}
```
becomes:
```
$ terraform apply
There are warnings and/or errors related to your configuration. Please
fix these before continuing.
Errors:
* At column 3, line 1: join: argument 1 should be type list, got type string in:
${join(",", var.astring)}
```
=> Pretty print types in error messages

convert.go, convert_test.go, eval.go
Previously `ast.Variable`'s were expanded only at the "top" level during evaluation. This causes a problem in Terraform when using lists or maps of other complex structures. This PR contains changes to rectify this, as well as a new VariableToInterface function which can be used outside of the package if necessary. Some older functionally similar but less elegant code is removed.
This forms part of fixing hashicorp/terraform#7143.
=> Expand all ast.Variables on evaluation

convert.go, convert_test.go
This pull request adds a check to the `InterfaceToVariable` helper to ensure that the input is not already wrapped with the HIL type annotations. If it is, the input is returned unmodified.
=> Test input for ast.Variable in InterfaceToVariable

builtins.go, eval_test.go
Fixes https://github.com/hashicorp/terraform/issues/7701
Go panics on divide by zero which causes really bad behavior for embedding HIL. This catches it and returns a nicer error.
=> Nice error instead of panic for divide by zero

.travis.yml, ast/index.go, eval_test.go
Functions nested in map indexes didn't have an argument stack, because
the index node hadn't been visited. Make sure we call Accept on the
index Key when it could be interpolated. We don't call it
unconditionally, because list indexes are assumed not be be pre Eval'ed.
Fixes https://github.com/hashicorp/terraform/issues/9282
=> Indexes may require further interpolation

ast/index.go, check_types.go, check_types_test.go, eval.go, eval_test.go
Fixes #28 
This fixes #28 but is also a general refactor, so the scope is a bit larger. 
The visitor pattern shouldn't discriminate what values are and are not
visited. This allows us to use the type checking stack and the eval
stack more properly and avoid evaling multiple nodes within the index
eval.
In turn, this enables all eval operations to work in both targets and
keys (fixes #28). We still enforce that the list target be a variable
access, however.
This also removes some type checking from eval since those type errors should be caught in the type checker itself and we should assume types are correct by the time they reach the evaluation step.
=> ast.Index should visit target and key

check_types.go, eval_test.go
HIL is a bit PHP-esque in that it does implicit string to number and
vice versa conversion where possible. For example `"2" - 1` equates to
1. This was a conscious decision made since without it, there ended up
being a LOT of explicit type conversion necessary since things like
counts in Terraform were/are strings.
This PR extends implicits to list and map index operations, allowing
variables that are potentially strings to be used as indexes without
type conversion operations (which don't exist right now, so you'd have
to do weird math tricks).
=> Support implicit conversion for list/map index key

ast/ast.go, ast/unknown.go, ast/variables_helper.go, check_types.go, check_types_test.go, convert.go, convert_test.go, eval.go, eval_test.go, eval_type.go
This is a special type (and sentinel value for InterfaceToVariable)
where any operation against it results in a TypeUnknown result. You can
see the tests to see how that works.
This is nice because if you have something like a function, map, or list
that DOESN'T result in an unknown value then the evaluation will work,
but if you happen to access an unknown value at runtime, hil as a whole
will return the unknown value immediately.
This helps Terraform tremendously because it can stop special casing
unknown values and actual mark them as such as just give them to HIL for
normal evaluation all the time. If HIL returns TypeUnknown, then
Terraform knows the value is computed. If in Terraform this happens at
apply-time, then its an error (no computed values during apply).
This has zero effect …
=> TypeUnknown for "unknown" values

ast/ast.go, ast/type_string.go, builtins.go, eval.go, eval_type.go, evaltype_string.go, lang.y, lex.go, lex_test.go, parse_test.go, y.go, y.output
This PR adds a new `TypeBool`. That allows us to write functions that
returns true or false. I think this is an important step for
https://github.com/hashicorp/terraform/issues/1604 as well
Here is an example `ast.Function` called `equal` that compares two
values and returns true or false (compiles with this PR).
https://play.golang.org/p/JpJ7GzA454
I've tried to check whether this breaks something, but right now it
passes all tests. Unfortunately I don't like the yacc parser, so it's
hard to understand it. Let me know if this is not suitable or if
something is wrong here.
=> Add bool type

eval_test.go, parser/binary_op.go, parser/parser.go, parser/parser_test.go
Previously all operators had equal precedence and they were all parsed in a left-associative manner. This was a simple rule, but it was counter-intuitive to people familiar with conventional expression notation or other languages with precedence rules.
Here we give multiplication and division higher precedence than addition and subtraction, so that e.g. `1+2*3` will parse as `1+(2*3)` rather than `(1+2)*3` as before. This is a breaking change for anyone that was depending on the old left-associative parsing behavior, but I assume that this will be relatively few people simply because the old behavior was so counter-intuitive that users are likely to have used explicit parentheses to make their code understandable.
This implementation just uses the standard Go stack to keep track of the …
=> Arithmetic operator precedence rules

parser/parser.go, parser/parser_test.go
Previously the scanner was correctly handling these but the parser was missing the case to replace the escape sequence with a literal quote, resulting in a parse error.
This fixes #35.
=> Correctly handle escaped quotes inside nested literals

ast/literal.go, ast/literal_test.go
Sometimes a caller wants to return a "synthetic" literal based on some Go value it is holding, such as a default placeholder value that can optionally be overridden by a HIL expression.
This new function helps callers do this robustly, selecting the appropriate value for the `Typex` attribute based on the dynamic type of the provided value.
For now this supports only primitive types. Later it could be interesting to support recursive construction of lists and maps from Go slices and maps, but for now we keep this relatively simple.
The primary motivation for this change is to support hashicorp/hcl#171.
=> LiteralNode factory function

parser/parser.go, parser/parser_test.go, scanner/scanner.go, scanner/scanner_test.go
This fixes #40 in a way that is consistent:
* Identifiers may not begin with numbers.
* Identifiers are parsed as a complete sequence, so "var.123" is
now a single identifier.
This should fix the case of variables and resource names starting with
numbers in Terraform without compromising on identifiers starting with
characters. This is because accessing these in Terraform is always
qualified with a prefix anyways.
I can see the use case for PERIOD being a separate token but its
unlikely we'll ever be able to use that for anything other than identifiers
due to historical reasons with HIL.
=> Parse "foo.bar" as a single identifier

check_types.go, eval_test.go
Fixes #43
If any element in a mathematical expression is a float, HIL should
promote the entire expression to float math.
=> promote to float math above all else

check_types.go, eval_test.go
This implicitly converts string to int or float for comparison operators
>, <, <=, >=.
=> implicitly convert string to numeric for comparison

ast/literal.go, eval.go, eval_test.go
Previously there was a hard rule that if a list or map contains any unknown values then the collection as a whole is unknown. This kept the handling of this situation in one spot, but was non-ideal since it is safe to use the index operator `[...]` on a partially-unknown list or map and access the values that *are* known.
This change removes the unilateral rule that any nested unknowns immediately collapse to a single top-level unknown, which then requires each of the eval node implementations to provide their own handling of unknowns. In return for this extra complexity, we are able to make an exception in the handling of the index operator to allow the retrieval of any known values in a partially-unknown collection.
The new rules are:
- If the ultimate evaluation result is a …
=> Allow partially-unknown collection values

ast/variables_helper.go, check_types.go, eval.go, eval_test.go
Earlier we made the evaluator support collections (lists and maps) that have a mixture of known and unknown members. However, since the type checker was not also aware of this it was short-circuiting as before and skipping type checking of any expression dependent on a value from a partially-unknown collection.
As well as missing some conversions, which was masked by the evaluator's own short-circuiting as expected, this also caused us to skip the conversion of arithmetic to built-in functions, which then caused the evaluator to fail since it doesn't have any support for direct evaluation of arithmetic.
This follows the same principle as the evalator changes: there's no longer a global rule that any partially-unknown value gets flattened to a total unknown when read from a variable, so …
=> Type checker awareness of partially-unknown collections

check_types.go, check_types_test.go, eval_test.go
In #52 we relaxed the rule that any unknown value would immediately cause an early exit, which in turn requires the type checker for each node to specifically deal with unknown values.
However, we missed dealing with the check that both types match in a conditional, causing a conditional to fail if either side of it is unknown.
This causes errors in Terraform, as described in hashicorp/terraform#14399.
=> Allow one or both conditional operands to be unknown

convert.go, convert_test.go, eval_test.go
This was discovered when upgrading `mitchellh/mapstructure` to its new version which contains https://github.com/mitchellh/mapstructure/pull/98 which in turn caused some tests in `hashicorp/terraform` to fail:
```
--- FAIL: TestInterpolateFuncMap (0.00s)
--- FAIL: TestInterpolateFuncMap/${map("hello",_list("world"),_"what's",_list("up?"))} (0.00s)
interpolate_funcs_test.go:2487: wrong result
given: ${map("hello", list("world"), "what's", list("up?"))}
got:   map[string]interface {}{"hello":map[string]interface {}{"Value":"world", "Type":"8"}, "what's":map[string]interface {}{"Value":"up?", "Type":"8"}}
want:  map[string]interface {}{"hello":[]interface {}{"world"}, "what's":[]interface {}{"up?"}}
--- FAIL: TestInterpolateFuncMerge (0.00s)
--- FAIL: …
```
=> InterfaceToVariable: Maintain backward compatibility

.circleci/config.yml
See https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 for context.
=> remove Codecov from CI

.github/CODEOWNERS
Add CODEOWNERS file to define code ownership rules.
This PR adds a CODEOWNERS file in `.github/CODEOWNERS` to help manage code review assignments and maintain clear ownership of different parts of the codebase.
=> Add team-ip-compliance to .github/CODEOWNERS file
